### ISSUE TITLE
New Kijiji Update Broke LoginFunction?

### ISSUE THREAD

**Issue by DudeManGuy0** [rybodiddly/Kijiji-Reposter#14]
I was writing my API and playing around with it when I noticed that login through mobile API no longer works. I tried this function using this repo and the same error happened. It said 'Sorry, your username or password is incorrect. Please try again.'. I tried logging in through Kijiji manually with the same creds and it worked just fine (not mobile, website instead). It's possible this is only on my end but give it a shot with your creds and see if the same error message occurs. On a side note, my token was invalidated which is why I tried to do this and it failed. Also if you know the endpoint for checking token validity please let me know what it is.

**Comment by AminDhouib** [comment]
I can confirm that the LoginFunction still works on my side. I erased my token.json file, inputted a new set of logins and it worked just fine. Consider using a different account or try again another time perhaps.

**Comment by DudeManGuy0** [comment]
It might somehow be because I uninstalled the Kijiji mobile app. Trying again today it still doesn't work. Idk how to fix this for myself but I'm going to close this issue now.

**Comment by rybodiddly** [comment]
Adding this for others who run into issues with api development: If you proxy the traffic with something like charles or proxyman, you'll notice that the mobile app uses a threat matrix. The api I use just circumvents it and ignores it. But if you spam the server during testing / development with redundant login attempts etc. It will lock you out for a period of time. So when doing development, be sure to have a vpn and a few different accounts to test with, because one usually gets locked down for a short period every so often from repeated and redundant traffic spamming the server. This is why I eventually created the token retention system, it allows the maintenance of a continous sessions, without numerous and unnecesasry logins.

**Comment by DudeManGuy0** [comment]
That's weird since I didn't spam, at least I don't think so.  Also what do you mean by "my api"? We are all using the same api, the mobile api, right? Also, running it through either Winscribe or Phisphon VPN doesn't make a difference

**Comment by rybodiddly** [comment]
Are you referring to my statement "The api I use"? If so, just referring to the api calls I actually utilize in the kijijiapi.py file. There were tons more, such as notifications etc. that just weren't implemented.

It's been a while, but I recall similar experiences to what you're experiencing. In my case they happened after successive login attempts. The login attempts may not have been the root cause. Could have been something on the mingle server's end. The mingle server can be extremely buggy and congested at times. But I specifically recall similar issues. I found it would eventually sort itself out and would just use a secondary account for the development. I also ran into it the odd time when testing multiple postings. Chalked it up to the threat matrix evasion or unnecessarily successive login attempts.
