### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'connect_timeout'

### ISSUE THREAD

**Issue by scsikid** [rybodiddly/Kijiji-Reposter#7]
Hello, running ubuntu 18. Using Python 3.6.9
This looking to be related to http2.0 anyone else having a problem with this?

```
$ python server.py
Traceback (most recent call last):
  File "server.py", line 450, in <module>
    timeout = httpx.Timeout(15.0, connect_timeout=30.0)
TypeError: __init__() got an unexpected keyword argument 'connect_timeout'
```

**Comment by rybodiddly** [comment]
Just attempted to replicate your issue. Received the following error while attempting to install httpx module into a python 3.6.9 environment: `The currently activated Python version 3.6.9 is not supported by the project (^3.7).
Trying to find and use a compatible version.` So my guess is your python version is below the current requirements of python 3.7. The official doc does say python 3.6+, but may need to be updated. Otherwise you will need to edit the timeout reference.

**Comment by rybodiddly** [comment]
Attempting to replicate. In the meantime, do me a favour and install / update your python to at least 3.8 and see if the issue persists.

**Comment by rybodiddly** [comment]
Issue corrected. httpx revision changed connect timeout argument from `connect_timeout` to just `connect`. Should be good to go now. download the new code and let me know if it works correctly.

**Comment by scsikid** [comment]
Solved! Thanks @rybodiddly
