### ISSUE TITLE
Coverting in No-SQL Database

### ISSUE THREAD

**Issue by hitman3r44** [rybodiddly/Kijiji-Reposter#8]
Hi,

I want to convert all the data coming from XML and JSON files data into MongoDB. I think that will more efficient to handle data. Do you have any idea how I am gonna start with this one??

**Comment by rybodiddly** [comment]
The specific reason for the use of xml is because the kijiji mingle server uses xml. Specifically, for the categories, locations and attributes utilized by the posting api. So for example, should kijiji change a couple attributes within certain posting categories, it would then break the posting process used by this server. But because this server uses the same xml formatting, updating it to use the same categories, location, attributes etc. is as simple as obtaining the new attributes files and dumping them in the `static` folder. So the main reason for the xml usage was to maintain future compatibility and keeps updating simple. Changing this to use something like mongoDB would mean having to reparse any future xml changes.

The JSON usage was implemented for small scale and simplicity.  Using JSON provides readability and allows easy editing. It was just a personal choice, but there's no reason why those components can't be used with mongodb, mysql or some other database. You would just need to retrieve data from or write data to a mongoDB instead of reading from or writing to a file. [This Link](https://kb.objectrocket.com/mongo-db/how-to-use-python-to-encode-a-json-file-into-mongodb-bson-documents-545) might provide you with some simple insight in how to take the already JSON formatted data and parse it into mongoDB.

**Comment by hitman3r44** [comment]
Thank you for the reply, totally understand the category, location, and other stuff. is there any way can we get this information with direct API calling from Kijiji. Something like I don't want to use any static value, in GUI from the drop-down menu can we get those values directly from API calling?

For trying to convert to into the database of the user posting information and scheduler so we can edit those stuff through the database. I will try the link you given to me. 

Also, want to convert the GUI into a new frontend framework like AngularJS, etc.
Also, want to user can administrate multiple Kijiji accounts.

**Comment by rybodiddly** [comment]
@hitman3r44 you could absolutely use dynamic api calls and do it on the fly. The only reason I went with static offline content was so my server didn't overload the mingle server. During initial development, I noticed the mobile mingle server is extremely slow and prone to timeouts. So minimal loads improves overall performance. Specifically in the conversations tab. I had to cut the # of messages retrieved down to 1/4 the original amount.

As for angular and managing multiple accounts, all seem like valid endeavours. Technically a user can manage unlimited accounts, as no account data is stored on the actual reposting server. All account data is retrieved from kijiji. So just log out of the reposter and log into the next account. But in terms of consolidating, I understand.

**Comment by hitman3r44** [comment]
Thanks for explaining the Kijiji problem, let me see what I can do.

**Comment by rybodiddly** [comment]
Update: Dynamic categories, locations and attributes have now been implemented. No more need for static XML files, plus categories, attributes etc. stay current.
